apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  http-context.conf: |-
    client_max_body_size 5M;
    upstream annif-app {
        server annif-app:8000;
    }
  server-context.conf: |-
    location /v1/ {
        proxy_pass http://annif-app;
    }
    location ~ \/v1/projects\/([^/]*)\/analyze$ {
        proxy_pass http://annif-app/v1/projects/$1/suggest;
    }
    location ~ \/v1/projects\/([^/]*)\/learn$ {
        deny  all;
    }
