apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |-
    worker_processes  1;

    error_log  /var/log/nginx/error.log warn;
    pid        /tmp/nginx.pid;

    events {
        worker_connections  1024;
    }


    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';
        log_format matomo '$http_x_forwarded_for - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent"';

        access_log  /var/log/nginx/access.log  main;
        ### TODO access_log /tmp/access.log matomo;
       

        sendfile        on;
        #tcp_nopush     on;

        keepalive_timeout  65;

        #gzip  on;

        ### include /etc/nginx/conf.d/*.conf;


        client_max_body_size 5M;
        upstream upstream_servers {
            server annif-app:8000;
        }
        server {
            listen 8080;
            server_name localhost;
            ### TODO root /webdata;
            
            # favicon does not exist:
            location = /favicon.ico {
                return 204;
                access_log     off;
                log_not_found  off;
            }
            location / {
                proxy_pass http://upstream_servers;
            }
            location ~ \/v1/projects\/([^/]*)\/analyze$ {
                proxy_pass http://upstream_servers/v1/projects/$1/suggest;
            }
            location ~ \/v1/projects\/([^/]*)\/learn$ {
                deny  all;
            }
        }
    }
