apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |-
    client_max_body_size 5M;
    upstream upstream_servers {
        server annif-app:8000;
    }
  default.conf: |-
    server_name localhost;

    location /v1/ {
        proxy_pass http://upstream_servers;
    }
    location ~ \/v1/projects\/([^/]*)\/analyze$ {
        proxy_pass http://upstream_servers/v1/projects/$1/suggest;
    }
    location ~ \/v1/projects\/([^/]*)\/learn$ {
        deny  all;
    }
