apiVersion: v1
kind: Service
metadata:
  name: annif-app
spec:
  selector:
    app: annif-app
  ports:
  - port: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
  - name: nginx
    port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: annif-app
  name: annif-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: annif-app
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: annif-app
    spec:
      containers:
        - image: quay.io/natlibfi/annif:0.52.0
          command: ["gunicorn", "annif:create_app()", "--bind", "0.0.0.0:8000", "--timeout", "600"]
          livenessProbe:
            exec:
              command: ["curl", "--fail", "localhost:8000/v1/projects"]
            failureThreshold: 3
            initialDelaySeconds: 600
            periodSeconds: 15
          name: annif-app
          resources: {}
          volumeMounts:
            - mountPath: /annif-projects
              name: model-data
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: model-data
          persistentVolumeClaim:
            claimName: model-data
            readOnly: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginxinc/nginx-unprivileged:1.20-alpine
          name: nginx
          resources: {}
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      restartPolicy: Always
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-conf
---
﻿kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: model-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: pomppa24
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: annif
  namespace: annif
  labels:
    type: external
spec:
  host: annif.ext.ocp-test-0.k8s.it.helsinki.fi
  port:
    targetPort: 8080
  to:
    kind: Service
    name: nginx
    weight: 100
  wildcardPolicy: None
